// Optimized icon imports to reduce bundle size
// Only import icons that are actually used in the dashboard

export {
  FaChartLine,
  FaDollarSign,
  FaFileAlt,
  FaFacebook,
  FaCheckCircle,
  FaClock,
  FaPercentage,
  FaEye,
  FaShareAlt,
  FaArrowRight,
  FaSignOutAlt,
  FaCalendarAlt,
  FaImage,
  FaVideo,
  FaEdit,
  FaBell,
  FaUser,
  FaCog,
  FaDownload,
  FaSearch,
  FaFilter,
  FaPlus,
  FaTrash,
  FaExclamationTriangle,
  FaCheck,
  FaTimes,
  FaStar,
  FaRocket,
  FaUsers,
  FaProjectDiagram,
  FaChartBar,
  FaCalendarCheck,
  FaMoneyBillWave,
  FaBullseye,
  FaTrophy,
  FaLightbulb,
  FaHandshake,
  FaComments,
  FaPaperPlane,
  FaFilePdf,
  FaFileExcel,
  FaBars,
  FaTimes as FaTimesIcon,
  FaInfo,
  FaCode,
  FaMobileAlt,
  FaSearchengin,
  FaCamera,
  FaFilm,
  FaChartArea,
  FaTasks,
  FaFolderOpen,
  FaFileWord,
  FaSpinner
} from 'react-icons/fa';
